version: '3.8'

services: 
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://deep_origin_owner:npg_V75bJtkenids@ep-withered-sea-a5vysgcr-pooler.us-east-2.aws.neon.tech/deep_origin?sslmode=require
      JWT_SECRET: asecretforauth
      BASE_URL: http://localhost:5001
    ports:
      - "5001:5001"
    command: sh -c "npx prisma migrate deploy && npm start"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5001/api

volumes:
  postgres_data:
